name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: '13.0'
    - name: Build the Docker image
      run: docker build 13.0/ --file 13.0/Dockerfile --tag odoo-ayphutec:13
